# BUILD metadata - autogenerated placeholder for CI diagnostics
BUILD_ID=placeholder-build-0001
BRANCH=main
COMMIT=0000000000000000000000000000000000000000
BUILDER=local-dev
TIMESTAMP=1970-01-01T00:00:00Z
NOTE=This file is a harmless placeholder used by CI/tooling to record build info.
